[package]
name = "rtdbg_runtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
colog = "1.3.0"
ctor = "0.4.2"
log = "0.4.27"
rhai = "1.22.0"
librtdbg = { path = "../librtdbg" }
libc = "0.2.174"
