[package]
name = "rtdbg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
nix = { version = "0.30.1", features = ["ptrace"] }
librtdbg = { path = "../librtdbg" }
